### ISSUE TITLE
Bottom shadow hidden on slideshow module

### ISSUE THREAD

**Issue by iafdesign** [bamboothemes/Boost#9]
On home page there is a zt2 slideshow  module - "Front Page Slideshow"
The image has a shadow shown on bottom and right of image in the slideshow. On the demo the grey band that holds the pagination discs is overlapping the image to prevent the shadow being seen. This may be by design or not!

**Comment by iafdesign** [comment]
Setting image style to none (in zt2) shows pagination (owl) is butted up to image.

**Comment by locii** [comment]
Yes this is by design. The grey stripe is meant to cut the image off so it tightens it up.
Thanks!
